name: e_com
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 3.0.1+8

environment:
  sdk: ">=2.14.2 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  path: ^1.8.0

    # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.4
  firebase_core: ^2.0.0
  firebase_messaging: ^14.0.0
  overlay_support: ^1.2.1


dependency_overrides:

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0
  fluttertoast: ^8.0.3
  local_auth: ^1.1.10
  flutter_staggered_grid_view: ^0.6.1
  persistent_bottom_nav_bar: ^4.0.2
  flutter_rating_bar: ^4.0.0
  percent_indicator: ^3.4.0
  carousel_slider: ^4.0.0
  flutter_widget_from_html: ^0.8.2
  url_launcher: ^6.0.20
  shared_preferences: ^2.0.5
  smooth_page_indicator: ^1.0.0+2
  dio: ^4.0.6
  image_picker: ^0.7.4
  pull_to_refresh: ^2.0.0
  build_runner: ^2.1.10
  mobx_codegen: ^2.0.5+2
  fancy_shimmer_image: ^2.0.2
  floor: ^1.1.0
  floor_generator: ^1.2.0
  mobx: ^2.0.6+1
  flutter_mobx: ^2.0.4
  razorpay_flutter: ^1.3.0
  speech_to_text: ^5.4.3
  avatar_glow: ^2.0.2
  http: ^0.13.4
  flutter_launcher_icons: ^0.9.2
  flutter_paystack: ^1.0.6
  upgrader: ^4.4.0
  flutter_stripe: ^5.1.0
  flutter_paypal: ^0.0.8
  fwfh_text_style: ^2.22.8+1
  win32: ^3.1.3
  device_info_plus: ^6.0.0

flutter_icons:

  image_path: "assets/images/launch.png"
  android: true
  ios: true




# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:

    - assets/images/background.jpg
    - assets/images/alert.png
    - assets/images/placeholder.png
    - assets/images/logo.png
    - assets/images/Logo2.png
    - assets/images/drop.png
    - assets/images/launch.png
    - assets/images/paypal.png

    - assets/images/BGinprofile.png
    - assets/images/BGheader.png
    - assets/icons/edit.png
    - assets/icons/ticket.png
    - assets/icons/DownIcon.png
    - assets/icons/star.png
    - assets/icons/Order.png
    - assets/icons/Chats.png
    - assets/icons/raz.png
    - assets/icons/Stripe.png
    - assets/icons/Paystack.png
    - assets/icons/Language.png
    - assets/icons/Helpcenter.png
    - assets/icons/Privacy.png
    - assets/icons/logout.png
    - assets/icons/radioFill.png
    - assets/icons/radio.png
    - assets/icons/share.png
    - assets/icons/delete.png
    - assets/icons/Minus.png
    - assets/icons/Plus.png
    - assets/icons/check.png
    - assets/icons/Phonepeicon.png
    - assets/icons/pey.png

    - assets/icons/NotificationButton.png


    - assets/images/backInPopup.png
    - assets/images/Successicon.png


    - assets/images/dropVerti.png
    - assets/images/noDataFound.png
    - assets/icons/selectedIcon.png
    - assets/icons/unselected.png
    - assets/icons/LogoDelete.png
    - assets/icons/logouticon.png
    - assets/icons/cancelIcon.png
    - assets/icons/cameraIcon.png
    - assets/icons/Gallery.png
    - assets/icons/sent.png



    - assets/icons/Downarrow.png
    - assets/icons/filter.png
    - assets/icons/sort.png
    - assets/icons/Switch.png
    - assets/icons/thumb.png
    - assets/icons/Calender.png
    - assets/icons/tag.png
    - assets/icons/offer.png
    - assets/icons/headPhone.png
    - assets/icons/watch.png
    - assets/icons/chat.png


    - assets/icons/mail.png
    - assets/icons/like.png
    - assets/icons/dislike.png
    - assets/icons/Arrow.png
    - assets/icons/phone.png
    - assets/icons/user.png
    - assets/icons/eyeicon.png
    - assets/icons/fingerprint.png
    - assets/icons/home.png
    - assets/icons/category.png
    - assets/icons/Menu.png

    - assets/icons/bell.png
    - assets/icons/cart.png
    - assets/icons/SearchIcon.png
    - assets/icons/mic.png
    - assets/icons/eyeshow.png




  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans-Bold.ttf

        - asset: assets/fonts/OpenSans-ExtraBold.ttf
          weight: 900

        - asset: assets/fonts/OpenSans-Light.ttf

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
